### ISSUE TITLE
React router integration

### ISSUE THREAD

**Issue by kahirul** [olance/rails-react-browserify-example#2]
I have similar setup with this repo. Do you manage to integrate react router to this setup for server rendering?

I tried before but not really working. For the moment I use [react-mini-router](https://github.com/larrymyers/react-mini-router).

**Comment by olance** [comment]
hey, I did manage this without any special setup: just `npm install`'d react-router and used it in my project.

What problem are you having?

**Comment by kahirul** [comment]
Everytime I hit my already defined route, the app is always render default route.
